version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
      image: circleci/classic:latest

    steps:
      - checkout

      - run:
          name: Install Base Requirements
          command: |
                    sudo apt update 
                    sudo apt install software-properties-common apt-transport-https gnupg2 curl make -y    
      - run:
          name: list directory
          command: ls -lha
                    
      - run: 
          name: run building test docker image
          command: make -C service-1 
